proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /home/fischerq/Documents/Tembryo/wisdota-nginx/vhosts:/etc/nginx/vhost.d:ro
webserver_dev:
  build: ../wisdota-webserver
  expose:
    - "42000"
  volumes:
    - /home/fischerq/Documents/Tembryo/wisdota-webserver/src:/source:ro
    - /home/fischerq/Documents/Tembryo/wisdota-webserver/files:/files:ro
    - /home/fischerq/Documents/Tembryo/wisdota-shared-code:/shared-code:ro
    - /home/fischerq/Documents/Tembryo/storage/webserver:/storage
    - /home/fischerq/Documents/Tembryo/storage/shared:/shared
  environment:
    VERSION: "DEV"
    VIRTUAL_HOST: "localhost"
    VIRTUAL_PORT: "42000"